[versions]
kotlin = "2.0.0"
kotlinx-serialization = "1.6.3"
shadow = "8.1.1"
run = "2.3.0"
paperweight = "1.7.1"

# Minecraft Software
folia = "1.20.6-R0.1-SNAPSHOT"
paper = "1.20.6-R0.1-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"

# Plugin Values
plugin-paper = "1.20"
plugin-folia = "1.20"

[libraries]
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version = "0.60.0" }

# Minecraft Software Dependencies
minecraft-server-folia = { group = "dev.folia", name = "folia-api", version.ref = "folia" }
minecraft-server-paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
minecraft-proxy-velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
paperweight-userdev = { id = 'io.papermc.paperweight.userdev', version.ref = "paperweight" }

# Run
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run" }